---
title: Biostatistical Consulting <br> Wastewater-based Epidemiology of COVID-19 in Athens,
  GA, USA 2020-2021
author: "Cody Dailey & Megan Lott <br> William Norfolk <br> Erin Lipp <br> Stephen Rathbun"
date: "2/11/2021"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: hide
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Preface {-}

This document will serve as a report among collaborators working on the analysis of wastewater surveillance data as part of a biostatistical consulting course (BIOS8200) instructed by Dr. Stephen Rathbun. The wastewater surveillance project was designed and implemented by Dr. Erin Lipp and her environmental health doctoral students, Megan Lott and William Norfolk. Megan Lott acts as the primary "client" for correspondence with lead "consultant" Cody Dailey, under the supervision of Dr. Stephen Rathbun and with meaningful discussion among other course consultants: Nicholas Mallis, Amanda Skarlupka, Morgan Taylor, and Adrianna Westbrook.


# Background

## SARS-CoV-2 and COVID-19 Pandemic

## Wastewater-based Epidemiological Surveillance

## Objectives
















# Methods

## Overview of Wastewater Sampling, Processing, and Analysis with Resulting Data

## Data Management and Cleaning

### Additional Data Sources

## Statistical Analysis

### Exploration of Association Structures

### Predictive Capabilities

# Results

## Data Description and Visualization

## Hypothesis Testing to Inference

## Predictions

# Discussion

